# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveSmallIntegerField(verbose_name='Revisión')),
                ('fecha', models.DateField(help_text='Fecha de aprobación de la revisión', verbose_name='Fecha')),
                ('politica', models.TextField(help_text='Contenido de la poítica de la calidad', verbose_name='Política')),
            ],
            options={
                'verbose_name': 'Política',
                'verbose_name_plural': 'Políticas',
            },
        ),
    ]
